include snippets/example/by_version/v3/by_context/http/server/mix_handle_404.conf;
include snippets/config/by_version/v3/by_app/by_name/fdn/app/common/inject_hijack_location.conf;

location = /just-cgi/debug/app/common {
    if ($fdn_forward_node_name = "") {
        set $fdn_forward_node_name fdn_common_server;
    }

    include snippets/example/by_version/v3/by_app/by_name/fdn/echo4debug/mix_echo4debug.conf;
}
