/// <reference types="njs-types/ngx_http_js_module.d.ts" />

const DOMAIN_REGEX = /^(?:[a-z0-9-]+\.)*([a-z]{2,})$/i;

/**
 * 简单遍历数组变量名，依次判断是否有效。
 * 如果都无效，则强制返回最后一个变量的值
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @param {string[]} varNames 变量数组
 * @returns 有效的变量的值
 */
function simpleJudgeVar(r, varNames) {
  let val;
  const arrLen = varNames.length;
  for (let i = 0; i < arrLen; i++) {
    const varName = varNames[i];
    val = r.variables[varName];
    if (val) {
      return val;
    }
  }

  // 默认强制返回最后一个元素
  return val;
}

/**
 * FoxyDockNginx 获取源头客户端 HTTP 请求的 URL 的 scheme 部分
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns 源头客户端请求协议
 */
function getFdnFirstClientUrlScheme(r) {
  // 优先尊重 X-Forwarded-Proto
  if (r.variables.http_x_forwarded_proto) {
    return r.variables.http_x_forwarded_proto;
  }

  if (r.variables.ssl_server_name) {
    return "https";
  }

  return simpleJudgeVar(r, ["http_x_forwarded_proto", "scheme"]);
}

// Generated by AI Qwen3-Coder
const IPv6_FLEX_HOSTNAME_ADDRESS_REGEX = /^\[(.*)\](?::\d+)?$/;

/**
 * 从符合 HTTP 请求头 Host 字段的字符串里提取出 HostName 部分
 * @param {string} theHost HTTP 请求头里的 Host 字段的值
 * @returns HostName 部分
 */
function extractHostName(theHost) {
  // 1. IPv6 专用正则：匹配 [ipv6]:port 格式，捕获组1 = ipv6
  var ipv6AddressMatch = theHost.match(IPv6_FLEX_HOSTNAME_ADDRESS_REGEX);
  if (ipv6AddressMatch) {
    return "[" + ipv6AddressMatch[1] + "]"; // 返回 "[ipv6]"
  }

  // 2. 其他情况：直接删掉末尾的 ":port"
  return theHost.replace(/:\d+$/, "");
}

/**
 * 获取 HTTP 请求头里的 HOST 字段里的 HostName 部分
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns HostName 部分
 */
function getHostName(r) {
  return extractHostName(r.variables.host);
}

/**
 * FoxyDockNginx 获取 HTTP 请求头里的 HOST 字段
 * QUIC 情况下拿不到 HTTP 请求头里的 HOST 字段。即 http_host 可能为空。
 * @param {NginxHTTPRequest} r NGINX 请求对象
 */
function getFdnJudgeHttpHost(r) {
  return simpleJudgeVar(r, ["http_host", "host"]);
}

/**
 * FoxyDockNginx 获取源头客户端 HTTP 请求的 URL 的 HostName 部分
 * @param {NginxHTTPRequest} r NGINX请求对象
 * @returns HostName 部分
 */
function getFdnFirstClientUrlHostname(r) {
  // 优先尊重 X-Forwarded-Host
  if (r.variables.http_x_forwarded_host) {
    return r.variables.http_x_forwarded_host;
  }

  const theHost = getFdnJudgeHttpHost(r);
  if (!theHost) {
    return theHost;
  }

  return extractHostName(theHost);
}

const IPV6_PORT_REGEX = /^\[[0-9a-f:]+\]:(\d+)$/i;
const NON_IPV6_PORT_REGEX = /^[^:\[][^:]*:(\d+)$/i;

/**
 * 获取 HTTP 请求头里的 HOST 字段里的端口号
 * @param {NginxHTTPRequest} r NGINX请求对象
 * @returns 套接字端口号
 */
function getHttpHostServerPort(r) {
  const httpHost = r.variables.http_host;
  if (!httpHost) {
    return "";
  }

  // 检查 IPv6 格式: [2001:db8::1]:8080
  let match = httpHost.match(IPV6_PORT_REGEX);
  if (match) {
    return match[1];
  }

  // 检查非 IPv6 格式: example.com:8080 或 192.168.1.1:8443
  match = httpHost.match(NON_IPV6_PORT_REGEX);
  if (match) {
    return match[1];
  }

  return "";
}

/**
 * FoxyDockNginx 获取源头客户端 HTTP 请求的 URL 的端口号部分
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns 套接字端口号
 */
function getFdnFirstClientUrlPort(r) {
  // 优先尊重 X-Forwarded-Port
  if (r.variables.http_x_forwarded_port) {
    return r.variables.http_x_forwarded_port;
  }

  // HTTP 请求头里的 HOST 理论上应该是最权威的。
  // 但如果是被反代了，可能 X-Forwarded-Port 和这里 port 不一致。
  // 毕竟 Host 字段传什么，一直没有定论
  // 所以以防万一，优先尊重 X-Forwarded-Port
  const httpHostServerPort = getHttpHostServerPort(r);
  if (httpHostServerPort !== "") {
    return httpHostServerPort;
  }

  return simpleJudgeVar(r, ["proxy_protocol_server_port", "server_port"]);
}

function isRemoteAddressStartsWithUnix(r) {
  return r.variables.remote_addr && r.variables.remote_addr.startsWith("unix:");
}

/**
 * 判断当前请求是否为本地 NGINX Stream 模块传入
 * @param {NginxHTTPRequest} r NGINX 请求对象
 */
function isIngressStreamForward(r) {
  return (
    isRemoteAddressStartsWithUnix(r) && r.variables.proxy_protocol_server_addr
  );
}

/**
 * 如果当前请求是 H3 请求，则直接返回 H3 情况下的 NGINX 原生变量
 * 如果当前请求不是 H3 ，则判断属于本地流转的情况才允许传递 FDN X 变量
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @param {string} h3CaseVarName 如果请求是 H3 的情况下允许传递的 NGINX 变量名，因为 NGINX 暂不支持 QUIC 走 UDS ，是 H3 则必属直达情况
 * @param {string} fdnHttpIngressXHeaderName NGINX 变量名
 * @returns 经过批准的变量值
 */
function getFdnHttpIngressXRoutedVal(
  r,
  h3CaseVarName,
  fdnHttpIngressXHeaderName
) {
  if (r.variables.http3) {
    return r.variables[h3CaseVarName];
  }

  return isRemoteAddressStartsWithUnix(r)
    ? r.variables[fdnHttpIngressXHeaderName]
    : void 0;
}

/**
 * FoxyDockNginx 获取当前 NGINX 网关所看到的源头客户端的请求协议
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns 当前 NGINX 网关所看到的源头客户端的请求协议
 */
function getFdnIngressScheme(r) {
  if (isIngressStreamForward(r)) {
    return r.variables.ssl_server_name ? "https" : "http";
  }

  return getFdnHttpIngressXRoutedVal(r, "scheme", "http_x_fdn_ingress_scheme");
}

/**
 * FoxyDockNginx 获取当前 NGINX 网关所看到的源头客户端的 HTTP 请求头里的 Host 字段
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns 获取当前 NGINX 网关所看到的源头客户端的 HTTP 请求头里的 Host 字段
 */
function getFdnIngressHost(r) {
  if (isIngressStreamForward(r)) {
    const theHostName = getHostName(r);
    const isTLS = getFdnIngressScheme(r) === "https";
    const theProxyProtocolServerPort = r.variables.proxy_protocol_server_port;
    let portNum;
    switch (theProxyProtocolServerPort) {
      case "443":
        portNum = isTLS ? void 0 : "443";
        break;
      case "80":
        portNum = isTLS ? "80" : void 0;
        break;
      default:
        portNum = theProxyProtocolServerPort;
        break;
    }

    return portNum ? `${theHostName}:${portNum}` : theHostName;
  }

  return getFdnHttpIngressXRoutedVal(
    r,
    "fdn_http3_compatible_host_for_proxy",
    "http_x_fdn_ingress_host"
  );
}

/**
 * FoxyDockNginx 获取当前 NGINX 网关所看到的源头客户端请求的服务器端口
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns 当前 NGINX 网关所看到的源头客户端请求的服务器端口
 */
function getFdnIngressServerPort(r) {
  if (isIngressStreamForward(r)) {
    return r.variables.proxy_protocol_server_port;
  }

  return getFdnHttpIngressXRoutedVal(
    r,
    "server_port",
    "http_x_fdn_ingress_server_port"
  );
}

/**
 * FoxyDockNginx 获取当前 NGINX 网关所看到的源头客户端的地址
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns 当前 NGINX 网关所看到的源头客户端的地址
 */
function getFdnIngressRemoteAddr(r) {
  if (isIngressStreamForward(r)) {
    return r.variables.proxy_protocol_addr;
  }

  return getFdnHttpIngressXRoutedVal(
    r,
    "remote_addr",
    "http_x_fdn_ingress_remote_addr"
  );
}

/**
 * FoxyDockNginx 生成 NGINX 网关 X-Forwarded-For 的值
 * @param {NginxHTTPRequest} r NGINX 请求对象
 * @returns X-Forwarded-For 的值
 */
function getFdnIngressXForwardedFor(r) {
  // 优先尊重 X-Forwarded-For
  if (r.variables.http_x_forwarded_for) {
    return r.variables.proxy_add_x_forwarded_for;
  }

  return `${getFdnIngressRemoteAddr(r)}, unix:`;
}

/**
 * 获取访问日志保存文件名
 * @param {NginxHTTPRequest} r NGINX 请求对象
 */
function getAccessLogFileName(r) {
  // 能提取出 fdn_app_name 时已经符合合法域名的要求
  const fdn_app_name = r.variables.fdn_app_name;
  if (fdn_app_name) {
    return `access_app_${fdn_app_name}.log`;
  }

  // 能匹配上 SSL 证书的有效域名
  const fdn_ssl_domain_name = r.variables.fdn_ssl_domain_name;
  if (fdn_ssl_domain_name) {
    return `access_tls_${fdn_ssl_domain_name}.log`;
  }

  // 纯 HTTP 请求但是 Host 有合法域名的
  const fdn_hostname = r.variables.fdn_hostname;
  if (DOMAIN_REGEX.test(fdn_hostname)) {
    return "access_plain_http.log";
  }

  // 未知的请求 例如纯 IP 地址访问
  return "access.log";
}

export default {
  extractHostName,
  getHostName,
  getHttpHostServerPort,
  getFdnJudgeHttpHost,

  getFdnFirstClientUrlScheme,
  getFdnFirstClientUrlHostname,
  getFdnFirstClientUrlPort,

  getFdnIngressScheme,
  getFdnIngressHost,
  getFdnIngressServerPort,
  getFdnIngressRemoteAddr,
  getFdnIngressXForwardedFor,

  getAccessLogFileName,
};
