# 启用SSL预读，不解密流量，只提取 SNI
ssl_preread on;
access_log /var/log/nginx/stream_proxy_relay_tls_access.log stream_proxy_relay_tls_server buffer=256m flush=2s;

proxy_protocol on;
proxy_pass $fdn_proxy_relay_tls_upstream;
