include snippets/example/by_version/v3/by_context/http/server/location/leaf_fdn_proxy_common_headers.conf;

proxy_set_header X-FDN-Ingress-Scheme $fdn_x_ingress_scheme;
proxy_set_header X-FDN-Ingress-Host $fdn_x_ingress_host;
proxy_set_header X-FDN-Ingress-Server-Port $proxy_protocol_port;
proxy_set_header X-FDN-Ingress-Remote-Addr $proxy_protocol_addr;
