include snippets/example/by_version/v3/by_context/http/server/mix_foxy_ssl.conf;
proxy_ssl_server_name on;
proxy_ssl_name $ssl_server_name;

set $fdn_x_ingress_server_port $proxy_protocol_server_port;
set $fdn_x_ingress_remote_addr $proxy_protocol_addr;

js_set $fdn_app_route_upstream fdn_ingress.buildFdnAppRouteUpstream;
