include snippets/example/by_version/v3/by_context/http/server/leaf_fdn_proxy_common_headers.conf;

js_set $fdn_x_ingress_forwarded_for http_var_map.getFdnIngressXForwardedFor;
proxy_set_header X-Forwarded-For $fdn_x_ingress_forwarded_for;
