include snippets/example/by_version/v3/by_context/http/server/mix_foxy_ssl.conf;
include snippets/example/by_version/v3/by_context/http/server/leaf_ssl_proxy_setting.conf;
include snippets/example/by_version/v3/by_context/http/server/leaf_default_http1p1_proxy_setting.conf;

js_set $fdn_x_ingress_forwarded_for http_var_map.getFdnIngressXForwardedFor;
proxy_set_header X-Forwarded-For $fdn_x_ingress_forwarded_for;
include snippets/example/by_version/v3/by_context/http/server/leaf_fdn_proxy_common_headers.conf;

js_set $fdn_app_route_upstream fdn_ingress.buildFdnAppRouteUpstream;
