set $fdn_forward_node_name fdn_default_ingress_server;
listen unix:/var/run/nginx/fdn_ingress_server_tls.sock ssl default_server;
include snippets/config/by_version/v3/by_app/by_name/fdn/app/ingress/inject_default_server.conf;

# 是的。你没看错。 default server 也用非 default 属性的 listen 指令。
# 原因是有全局的 default server 兜底。 snippets/example/by_version/v3/by_context/http/server/mix_default_tls_server.conf
include snippets/example/by_version/v3/by_context/http/server/mix_listen.conf;
include snippets/example/by_version/v3/by_app/by_name/fdn/app/ingress/router/mix_server_setting.conf;
