set $fdn_forward_node_name proxy_protocol_uds_client_tls_server;
listen unix:/var/run/nginx/fdn_proxy_protocol_client_server_tls.sock ssl proxy_protocol default_server;
real_ip_header proxy_protocol;

include snippets/example/by_version/v3/by_context/http/server/mix_foxy_ssl.conf;
include snippets/example/by_version/v3/by_context/http/server/leaf_ssl_proxy_setting.conf;
include snippets/example/by_version/v3/by_context/http/server/leaf_default_http1p1_proxy_setting.conf;
include snippets/example/by_version/v3/by_context/http/server/mix_fdn_proxy_headers.conf;

location / {
    proxy_pass https://unix:/var/run/nginx/fdn_ingress_server_tls.sock;
}
