include snippets/example/by_version/v3/by_context/http/server/mix_h3_and_forward.conf;

js_set $fdn_app_upstream fdn_ingress.buildFdnAppUpstream;

include snippets/config/by_version/v3/by_app/by_name/fdn/app/common/inject_server_no_location_setting.conf;
