listen 0.0.0.0:2082 default_server reuseport;
listen 0.0.0.0:8080 default_server reuseport;
listen 0.0.0.0:8880 default_server reuseport;
listen    [::]:2082 default_server reuseport;
listen    [::]:8080 default_server reuseport;
listen    [::]:8880 default_server reuseport;
