include snippets/example/by_version/v3/by_context/http/server/mix_fdn_proxy_headers.conf;
include snippets/example/by_version/v3/by_context/http/server/leaf_default_http1p1_proxy_setting.conf;
include snippets/example/by_version/v3/by_context/http/server/leaf_ssl_proxy_setting.conf;
