include snippets/example/by_version/v3/by_context/http/server/location/leaf_ssl_upgrade_headers.conf;
include snippets/example/by_version/v3/by_context/http/server/location/leaf_fdn_auto_disable_buffering.conf;

# auth_basic $fdn_app_auth_basic_title;
# auth_basic_user_file $fdn_app_auth_htpasswd_file;
