log_format stream_ingress_tls_server escape=json '{'
'"remote_addr":"$remote_addr",'
'"time_iso8601":"$time_iso8601",'
'"ssl_preread_server_name":"$ssl_preread_server_name",'
'"preset_ingress_tls_upstream":"$preset_ingress_tls_upstream",'
'"fdn_ingress_tls_upstream":"$fdn_ingress_tls_upstream",'
'"protocol":"$protocol",'
'"status":"$status",'
'"bytes_sent":"$bytes_sent",'
'"bytes_received":"$bytes_received",'
'"session_time":"$session_time",'
'"upstream_addr":"$upstream_addr",'
'"upstream_bytes_sent":"$upstream_bytes_sent",'
'"upstream_bytes_received":"$upstream_bytes_received",'
'"upstream_connect_time":"$upstream_connect_time"'
'}';

log_format stream_proxy_relay_tls_server escape=json '{'
'"remote_addr":"$remote_addr",'
'"time_iso8601":"$time_iso8601",'
'"ssl_preread_server_name":"$ssl_preread_server_name",'
'"preset_proxy_relay_tls_upstream":"$preset_proxy_relay_tls_upstream",'
'"fdn_proxy_relay_tls_upstream":"$fdn_proxy_relay_tls_upstream",'
'"protocol":"$protocol",'
'"status":"$status",'
'"bytes_sent":"$bytes_sent",'
'"bytes_received":"$bytes_received",'
'"session_time":"$session_time",'
'"upstream_addr":"$upstream_addr",'
'"upstream_bytes_sent":"$upstream_bytes_sent",'
'"upstream_bytes_received":"$upstream_bytes_received",'
'"upstream_connect_time":"$upstream_connect_time"'
'}';
