server {
    include snippets/config/by_version/v3/by_context/stream/server/inject_proxy_relay_tls_server_setting.conf;
    include snippets/example/by_version/v3/by_context/stream/server/leaf_proxy_relay_tls_server_setting.conf;
}
