# $ssl_preread_server_name 即为请求域名
map $ssl_preread_server_name $fdn_sni {
    default $ssl_preread_server_name;
}

include snippets/example/by_version/v3/by_context/http/leaf_map_fdn_sni___preset_ssl_domain_name.conf;
