map "${ssl_preread_server_name}_${preset_ssl_domain_name}" $preset_proxy_relay_tls_upstream {
    include snippets/config/by_version/v3/by_context/stream/map_sni___preset_proxy_relay_tls_upstream.conf;
    "~*^.+_.+$"    unix:/var/run/nginx/fdn_proxy_protocol_client_server_tls.sock;
    default        "";
}

map "${preset_proxy_relay_tls_upstream}" $fdn_proxy_relay_tls_upstream {
    ''         stream_eof;
    default    $preset_proxy_relay_tls_upstream;
}
