map "${ssl_preread_server_name}_${preset_ssl_domain_name}" $preset_ingress_tls_upstream {
    include snippets/config/by_version/v3/by_context/stream/map_sni___preset_ingress_tls_upstream.conf;
    default        "";
}

map "${preset_ingress_tls_upstream}" $fdn_ingress_tls_upstream {
    ''         stream_eof;
    default    $preset_ingress_tls_upstream;
}
